steps:
- name: 'golang:1.11.5-stretch'
  entrypoint: 'go'
  args: ['build', '.']
  env: ['GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/metal-tile/land/$BRANCH_NAME:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/metal-tile/land/$BRANCH_NAME:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment/land-node
    - land-node=gcr.io/$PROJECT_ID/metal-tile/land/$BRANCH_NAME:$COMMIT_SHA
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=metal-tile'
images: ['gcr.io/$PROJECT_ID/metal-tile/land/$BRANCH_NAME:$COMMIT_SHA']